<?php


namespace App\Enum\Type;


use HoangDo\Authorization\Enum\BaseRole;

class Role extends BaseRole
{
    const CAN_MANAGE_PRODUCTS = 'ROLE_CAN_MANAGE_PRODUCTS';
    const CAN_MANAGE_USERS = 'ROLE_CAN_MANAGE_USERS';
    const CAN_MANAGE_REWARDS = 'ROLE_CAN_MANAGE_REWARDS';
    const CAN_MANAGE_ARTICLES = 'ROLE_CAN_MANAGE_ARTICLES';
    const CAN_MANAGE_BANNERS = 'ROLE_CAN_MANAGE_BANNERS';
    const CAN_MANAGE_BOTS = 'ROLE_CAN_MANAGE_BOTS';
    const CAN_MANAGE_NOTIFICATIONS = 'ROLE_CAN_MANAGE_NOTIFICATIONS';
    const CAN_MANAGE_TRANSACTIONS = 'ROLE_CAN_MANAGE_TRANSACTIONS';
}
